// import { EMPLOYELEARNINGDATA } from './../Model/employe-data';
import { EmployeeLearningData } from './../Model/employe';
import { Employe } from "../Model/employe";
import { HttpClient } from '@angular/common/http';
import { Injectable, OnInit } from "@angular/core";
import { Observable, map, of } from "rxjs";

@Injectable({
    providedIn: 'root'
})

export class EmployeService implements OnInit {

    employeData: Employe[] = []
    employeLearningData: EmployeeLearningData[] = [
        {
            "emp_id": "4011",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Microsoft Azure Fundamentals - 101",
            "certification_two": "Amazon Web Services",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "70",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "08-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "15-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Okay"
        },
        {
            "emp_id": "4012",
            "training_batch": "Batch 1",
            "joining_psl": "undefined",
            "wfo_date": "18-Aug-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "30",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Fail",
            "advance_training_start_date": "16-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Hey"
        },
        {
            "emp_id": "4013",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "80",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4014",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Microsoft Azure 900",
            "certification_two": "Amazon Web Services",
            "certification_three": "Microsoft Azure Fundamentals - 101",
            "foundation_track": "C++",
            "score": "30",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Fail",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2024",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4015",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4016",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4017",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "70",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4018",
            "training_batch": "Batch 1",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "null",
            "certification_three": "null",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4019",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "78",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4020",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4021",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI Angular",
            "score": "75",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Good!"
        },
        {
            "emp_id": "4022",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4023",
            "training_batch": "Batch3",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Microsoft Azure Fundamentals - 101",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "Java",
            "score": "100",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-01-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4024",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "18-Aug-22",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "UI React",
            "score": "69",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Fail",
            "advance_training_start_date": "16-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Okay"
        },
        {
            "emp_id": "4025",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "11-11-2022",
            "foundation_end_date": "11-12-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4026",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4027",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4028",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4029",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4030",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4031",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4032",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4033",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4034",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4035",
            "training_batch": "Batch3",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Microsoft Azure Fundamentals - 101",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "Java",
            "score": "100",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-01-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4036",
            "training_batch": "Batch2",
            "joining_psl": "Yes",
            "wfo_date": "18-Aug-22",
            "certification": "Java",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "Angular",
            "score": "70",
            "foundation_start_date": "16-Sep-22",
            "foundation_end_date": "16-Sep-22",
            "foundation_performance": "pass",
            "advance_training_start_date": "16-Sep-22",
            "advance_training_end_date": "16-Sep-22",
            "alp_start_date": "16-Sep-22",
            "alp_end_date": "16-Sep-22",
            "training_completion_date": "16-Sep-22",
            "current_training": "Juipter",
            "current_BU": "DPE",
            "l_and_d_comments": "Okay"
        },
        {
            "emp_id": "4037",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4038",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4039",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4040",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4041",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4042",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4043",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4044",
            "training_batch": "Batch3",
            "joining_psl": "Yes",
            "wfo_date": "16-Sep-22",
            "certification": "Java",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "Angular",
            "score": "70",
            "foundation_start_date": "16-Sep-22",
            "foundation_end_date": "16-Sep-22",
            "foundation_performance": "pass",
            "advance_training_start_date": "16-Sep-22",
            "advance_training_end_date": "16-Sep-22",
            "alp_start_date": "16-Sep-22",
            "alp_end_date": "16-Sep-22",
            "training_completion_date": "16-Sep-22",
            "current_training": "Juipter",
            "current_BU": "DPE",
            "l_and_d_comments": "Okay"
        },
        {
            "emp_id": "4045",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4046",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4047",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "16-Sep-22",
            "certification": "Amazon Web Services",
            "certification_two": "NULL",
            "certification_three": "NULL",
            "foundation_track": "UI Angular",
            "score": "91",
            "foundation_start_date": "16-09-2022",
            "foundation_end_date": "16-09-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "25-09-2022",
            "advance_training_end_date": "16-09-2022",
            "alp_start_date": "16-09-2022",
            "alp_end_date": "16-09-2022",
            "training_completion_date": "16-09-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Not Okay"
        },
        {
            "emp_id": "4048",
            "training_batch": "Batch2",
            "joining_psl": "undefined",
            "wfo_date": "NULL",
            "certification": "Amazon Web Services",
            "certification_two": "Microsoft Azure Fundamentals - 101",
            "certification_three": "Microsoft Azure 900",
            "foundation_track": "Java",
            "score": "100",
            "foundation_start_date": "01-01-2022",
            "foundation_end_date": "17-11-2022",
            "foundation_performance": "Pass",
            "advance_training_start_date": "01-01-2022",
            "advance_training_end_date": "01-01-2022",
            "alp_start_date": "01-01-2022",
            "alp_end_date": "01-01-2022",
            "training_completion_date": "01-01-2022",
            "current_training": "undefined",
            "current_BU": "undefined",
            "l_and_d_comments": "Training Completed"
        }
    ]
    singleLearningData: EmployeeLearningData
    id: number

    constructor(private http: HttpClient) {
        this.getEmployes()
    }

    ngOnInit() {
        this.getEmployes()
        console.log(this.employeData)
    }

    getEmployes() {
        return this.http.get<Employe[]>('https://sheetdb.io/api/v1/4ynn8dyy80f1p')
            .pipe(map(responseData => {
                const employeArray: Employe[] = [];
                for (const key in responseData) {
                    employeArray.push(responseData[key])
                }
                return employeArray
            }))
    }

    /////////////////////////////////////

    getEmployesById(id: number): any {
        return this.http.get<Employe>(`https://sheetdb.io/api/v1/4ynn8dyy80f1p`)
    }

    getEmployeCardDetails(id: number): any {
        return this.http.get(`https://sheetdb.io/api/v1/4ynn8dyy80f1p`)
    }

    getEmployeLearningDataById(id: number) {
        this.id = id
        console.log(this.employeLearningData.filter(e => parseInt(e.emp_id) === id))
        // return of(this.employeLearningData.filter(e => parseInt(e.emp_id) === id))
    }

    updateLearningDataByID(dataVal: any, id: number) {
        const headers = {
            "Content-Type": "application/json",
            Accept: "application/json",
            'My-Custom-Header': 'foobar'
        }
        return this.http.put(`https://sheetdb.io/api/v1/ggrrjfi1jszhj/${id}/edit`, dataVal)
    }

    createNewEmployeUsingPost(data: EmployeeLearningData) {
        return this.http.post(`http://localhost:4000/new-employe`, data)
    }

}
