// import { EmployeeLearningData } from "./employe";

// export const EMPLOYELEARNINGDATA: EmployeeLearningData[] =

//   // [

//   //     {
//   //         "emp_code":49880,
//   //         "Training_Batch":"Batch 3",
//   //         "Certifications":"Azure",
//   //         "Mapped_Skills":"JAVA FULL STACK",
//   //         "Final_Skills":"JAVA",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 10",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"70%",
//   //         "Special_Training_Start_Date":"MAY 20",
//   //         "Advanced_Special_Training_End_Date":"JUN 25",
//   //         "ALP_Start_Date":"JUN 28",
//   //         "ALP_End_Date":"JULY 18",
//   //         "Training_Completion_Date":"JULY 18",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     },
//   //     {
//   //         "emp_code":49215,
//   //         "Training_Batch":"Batch 2",
//   //         "Certifications":"SAG",
//   //         "Final_Skills":"ReactJS",
//   //         "Mapped_Skills":"ReactJS",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 18",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"100%",
//   //         "Special_Training_Start_Date":"MAY 22",
//   //         "Advanced_Special_Training_End_Date":"JUN 25",
//   //         "ALP_Start_Date":"JUN 29",
//   //         "ALP_End_Date":"JULY 18",
//   //         "Training_Completion_Date":"JULY 18",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"

//   //     },
//   //     {
//   //         "emp_code":49198,
//   //         "Training_Batch":"Batch 2",
//   //         "Certifications":"Azure",

//   //         "Final_Skills":"JAVA",
//   //         "Mapped_Skills":"JAVA FULL STACK",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 18",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"80%",
//   //         "Special_Training_Start_Date":"MAY 25",
//   //         "Advanced_Special_Training_End_Date":"JUN 25",
//   //         "ALP_Start_Date":"AUG 1",
//   //         "ALP_End_Date":"SEP 28",
//   //         "Training_Completion_Date":"SEP 28",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     },
//   //     {
//   //         "emp_code":46797,
//   //         "Training_Batch":"Batch 1",
//   //         "Certifications":"SAG",

//   //         "Final_Skills":"PYTHON",
//   //         "Mapped_Skills":"PYTHON",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 10",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"90%",
//   //         "Special_Training_Start_Date":"MAY 15",
//   //         "Advanced_Special_Training_End_Date":"JULY 25",
//   //         "ALP_Start_Date":"JUN 29",
//   //         "ALP_End_Date":"AUG 25",
//   //         "Training_Completion_Date":"AUG 28",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     },
//   //     {
//   //         "emp_code":49990,
//   //         "Training_Batch":"Batch 1",
//   //         "Certifications":"Azure",

//   //         "Final_Skills":"JAVA FULL STACK",
//   //         "Mapped_Skills":"JAVA FULL STACK",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 10",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"70%",
//   //         "Special_Training_Start_Date":"MAY 20",
//   //         "Advanced_Special_Training_End_Date":"JUN 25",
//   //         "ALP_Start_Date":"JUN 28",
//   //         "ALP_End_Date":"JULY 18",
//   //         "Training_Completion_Date":"JULY 18",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     },
//   //     {
//   //         "emp_code":49562,
//   //         "Training_Batch":"Batch 1",
//   //         "Certifications":"Azure",
//   //         "Final_Skills":"UI-ANGULAR",
//   //         "Mapped_Skills":"UI-ANGULAR",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 5",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"80%",
//   //         "Special_Training_Start_Date":"MAY 7",
//   //         "Advanced_Special_Training_End_Date":"JUN 20",
//   //         "ALP_Start_Date":"JUN 26",
//   //         "ALP_End_Date":"JULY 18",
//   //         "Training_Completion_Date":"JULY 18",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     },
//   //     {
//   //         "emp_code":49265,
//   //         "Training_Batch":"Batch 2",
//   //         "Certifications":"Azure",

//   //         "Final_Skills":"PYTHON",
//   //         "Mapped_Skills":"PYTHON",
//   //         "Foundation_Start_Date":"FEB 25",
//   //         "Foundation_End_Date":"MAY 18",
//   //         "Performance":"PASS",
//   //         "Foundation_Score":"85%",
//   //         "Special_Training_Start_Date":"MAY 21",
//   //         "Advanced_Special_Training_End_Date":"JUN 26",
//   //         "ALP_Start_Date":"JUN 28",
//   //         "ALP_End_Date":"AUG 18",
//   //         "Training_Completion_Date":"AUG 18",
//   //         "In_Training":"YES",
//   //         "LandD":"NA"
//   //     }


//   // ]


//   [
//     {
//       emp_id: 4011,
//       training_batch: "Batch1",
//       joining_psl: 'Joined NOO',
//       wfo_date: 'To report by July end. NOOO',
//       certification: 'Microsoft Azure 101',
//       foundation_track: "Java",
//       score: 70,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '13-May-2022',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Jul-22',
//       advance_training_end_date: '5-Aug-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '2-Sep-22',
//       training_completion_date: '5-Aug-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: "",
//     },
//     {
//       emp_id: 4012,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Amazon Web Services',
//       certification_one: "",
//       foundation_track: 'UI-React',
//       score: 80,
//       foundation_start_date: '20-May-2022',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-23',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments'
//     },
//     {
//       emp_id: 4013,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: 'C++',
//       score: 65,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     },
//     {
//       emp_id: 4014,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: 'Java Full Stack',
//       score: 65,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     },
//     {
//       emp_id: 4015,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: 'Python',
//       score: 65,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     },
//     {
//       emp_id: 4016,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: '.Net',
//       score: 86,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     },
//     {
//       emp_id: 4017,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: 'Java',
//       score: 65,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     },
//     {
//       emp_id: 4018,
//       // training_batch: ['Batch1',"Batch2","Batch3"],
//       training_batch: "Batch1",
//       joining_psl: 'Joined',
//       wfo_date: 'To report by August end.',
//       certification: 'Cloud',
//       foundation_track: 'UI-Angular',
//       score: 65,
//       foundation_start_date: '28-Feb-22',
//       foundation_end_date: '15-May-22',
//       foundation_performance: 'pass',
//       advance_training_start_date: '5-Aug-22',
//       advance_training_end_date: '5-Sep-22',
//       alp_start_date: '8-Aug-22',
//       alp_end_date: '29-Sep-22',
//       training_completion_date: '5-Sep-22',
//       current_training: 'Jupiter Ascending',
//       current_BU: 'DPE',
//       l_and_d_comments: 'Waiting for comments',
//       certification_one: ""
//     }
//   ]
